---
# worker_nodes: join worker nodes to the cluster (incomplete)

- name: Pull images on NON-primary control nodes
  when: inventory_hostname != primary_control_node
  block:
    - name: Pull images required for setting up k8s cluster
      ansible.builtin.command:
        cmd: "kubeadm config images pull"
      changed_when: true

- name: Generate a certificate key
  ansible.builtin.command:
    cmd: kubeadm certs certificate-key
  register: __control_nodes_cert_key
  changed_when: false
  no_log: true

- name: Upload the control plane certificates
  ansible.builtin.command:
    cmd: >-
      kubeadm init phase upload-certs --upload-certs
      --certificate-key {{ __control_nodes_cert_key['stdout'] }}
  changed_when: true
  no_log: true

- name: Generate a join command
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: __control_nodes_join_command
  changed_when: true
  no_log: true
...
