---
# tasks file for common

- name: Qemu guest agent
  block:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
    
    - name: Enable and start qemu-guest-agent service
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started

- name: Install misc packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
  when: common_packages | default([]) | length > 0

- name: Configure chrony
  ansible.builtin.import_tasks:
    file: chrony.yml

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: "{{ timezone }}"

- name: Populate hosts file with cluster systems
  block:
    - name: Stop cloud-init from managing /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^\s*-\s+update_etc_hosts\s*$'
        state: absent

    - name: Place hosts file tempate
      ansible.builtin.template:
        dest: /etc/hosts
        force: true
        group: root
        mode: '0644'
        owner: root
        src: templates/hosts.j2

- name: Enable persistent logging for the systemd journal
  block:
    - name: Set storage option to persistent in journald.conf
      community.general.ini_file:
        create: false
        exclusive: true
        modify_inactive_option: true
        no_extra_spaces: true
        option: Storage
        section: Journal
        path: /etc/systemd/journald.conf
        value: persistent
        state: present

    - name: Restart systemd-journald
      ansible.builtin.systemd_service:
        name: systemd-journald
        state: restarted
        daemon-reload: true

    - name: Restart and flush journald
      ansible.builtin.command:
        cmd: journalctl --flush
      changed_when: false

- name: Set "ll" alias for "ls" command
  # Becuase I like it
  ansible.builtin.lineinfile:
    line: >-
      alias ll='ls -lah' 2>/dev/null
      alias l.='ls -dah .*' 2>/dev/null
    create: true
    dest: /etc/profile.d/ls-alias.sh
    mode: '0644'
    group: root
    owner: root
    state: present
    # -n flag means "noexec"
    validate: 'bash -n %s'

- name: Install and configure k8s basics
  when: 
    ('control_nodes' in group_names) or
    ('worker_nodes' in group_names)
  ansible.builtin.import_tasks:
    file: k8s_nodes.yml
...