---
# common: default variables

common_timezone: "America/Chicago"
common_qemu_guest_agent: true
common_journald_persistent: true
common_packages:
  - tree
  - vim
  - apt-file
  - needrestart
common_k8s_prereq_packages:
  - fio
  - conntrack          # kube-proxy needs it
  - socat              # kubectl port-forward needs it
  - ethtool            # CNI plugins use it for interface config
  - nftables
  - netcat-openbsd
  - containerd

## Time
common_ntp_sources:
  - directive: server
    address: 172.16.1.1
    options: iburst maxpoll 8
  - directive: server
    address: 10.0.1.1
    options: iburst maxpoll 8
  - directive: pool
    address: time.nist.gov
    options: iburst maxsources 2
  - directive: server
    address: time.cloudflare.com
    options: iburst
common_ntp_verify: true
common_ntp_minsources: 2

## CRI
common_containerd_systemdcgroup: true

## k8s
common_k8s_hold_packages:
  - kubeadm
  - kubelet
  - kubectl
...
