---
# install Calico CNI on primary control node

- name: Place calico custom resource file
  ansible.builtin.template:
    dest: /root/calico-installation.yaml
    force: true
    group: root
    mode: '0644'
    owner: root
    src: calico-installation.yaml.j2

- name: Install Calico
  block:
    - name: Install custom resource definitions
      ansible.builtin.command:
        cmd: >-
          kubectl apply --server-side
          -f https://raw.githubusercontent.com/projectcalico/calico/v3.32.1/manifests/v1_crd_projectcalico_org.yaml
      register: __control_nodes_calico_crds
      changed_when: "'unchanged' not in __control_nodes_calico_crds['stdout']"

    - name: Install Tigera operator
      ansible.builtin.command:
        cmd: >-
          kubectl apply
          -f https://raw.githubusercontent.com/projectcalico/calico/v3.32.1/manifests/tigera-operator.yaml
      register: __control_nodes_calico_operator
      changed_when: "'unchanged' not in __control_nodes_calico_operator['stdout']"

    - name: Wait for the Installation CRD to be established
      ansible.builtin.command:
        cmd: >-
          kubectl wait --for=condition=Established
          crd/installations.operator.tigera.io --timeout=120s
      changed_when: false

    - name: Install Calico with resource file
      ansible.builtin.command:
        cmd: "kubectl apply -f /root/calico-installation.yaml"
      register: __control_nodes_calico_install
      changed_when: >-
        'created' in __control_nodes_calico_install['stdout'] or
        'configured' in __control_nodes_calico_install['stdout']

- name: Wait for the Calico status object to appear
  ansible.builtin.command:
    cmd: "kubectl wait --for=create tigerastatus/calico --timeout=120s"
  changed_when: false

- name: Wait for Calico to become available
  ansible.builtin.command:
    cmd: >-
      kubectl wait --for=condition=Available
      tigerastatus/calico --timeout=300s
  changed_when: false
...