---
- name: Create .kube directory in home dir
  ansible.builtin.file:
    force: true
    group: root
    mode: '0755'
    owner: root
    state: directory
    path: "/root/.kube"

- name: Copy admin.conf to home dir
  ansible.builtin.copy:
    backup: false
    force: true
    group: root
    mode: '0644'
    owner: root
    remote_src: true    # true=file is on the target node
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config_{{ cluster_name }}"

- name: Create kubeconfig on localhost
  when: create_kubeconfig_on_localhost
  block:
    - name: Create .kube directory in home dir
      ansible.builtin.file:
        force: true
        group: root
        mode: '0755'
        owner: root
        state: directory
        path: "/home/{{ ansible_user }}/.kube"
      delegate_to: localhost

    - name: Copy admin.conf to home dir
      ansible.builtin.fetch:
        fail_on_missing: true
        flat: true
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config_{{ cluster_name}}"
      delegate_to: localhost
...