---
- name: Configure control node prerequisites
  ansible.builtin.import_tasks:
    file: prereqs.yml

- name: Configure containerd
  ansible.builtin.import_tasks:
    file: containerd.yml

- name: Configure k8s repo and install k8s packages
  ansible.builtin.import_tasks:
    file: repo.yml

- name: Place crictl.yaml config file
  ansible.builtin.copy:
    force: true
    owner: root
    mode: '0644'
    group: root
    remote_src: false               # false=file is on Ansible controller node
    src: crictl.yaml                # .yml will be ignored, must be .yaml
    dest: /etc/crictl.yaml

- name: Pull images on NON-primary control nodes
  when: inventory_hostname != primary_control_node
  block:
    - name: Pull images required for setting up k8s cluster
      ansible.builtin.command:
        cmd: "kubeadm config images pull"
      changed_when: true

- name: Pull images and bootstrap primary control node
  when: inventory_hostname == primary_control_node
  block:
    - name: Determine if control plane is already up
      ansible.builtin.command:
        cmd: "kubectl --kubeconfig /etc/kubernetes/admin.conf get --raw /healthz"
      register: control_plane_healthz
      changed_when: false
      failed_when: false

    - name: Create kubeadm config file
      ansible.builtin.template:
        dest: /root/kubeadm-config.yaml
        force: true
        group: root
        mode: '0644'
        owner: root
        src: kubeadm-config.yaml.j2
      when: control_plane_healthz['rc'] != 0    # Intent: prevent config command from being re-run on a working control node, which would fail.

    - name: Bootstrap the primary Kubernetes control node
      ansible.builtin.command:        
        cmd: >-
          kubeadm init
          --config /root/kubeadm-config.yaml
          --upload-certs
        # creates: /etc/kubernetes/admin.conf     
      changed_when: true
      when: control_plane_healthz['rc'] != 0    # Intent: prevent config command from being re-run on a working control node, which would fail.

- name: Install Calico CNI on primary control node
  when: inventory_hostname == primary_control_node
  ansible.builtin.import_tasks:
    file: calico.yml

- name: Copy kubeconfig to home dirs
  ansible.builtin.import_tasks:
    file: kubeconfig.yml

# - name: Join cn02
#   block:
#     - name: Join cn02
#       anisble.builtin.command:
#         cmd: >-
#           kubeadm join d-k8s-api.opnsense.lab:6443 \
#             --token <token> \
#             --discovery-token-ca-cert-hash sha256:<hash> \
#             --control-plane \
#             --certificate-key <key> \
#             --apiserver-advertise-address 172.16.1.105

# Look at this section: "11. Join cn02 and cn03". It sucks. Please improve and expand it. Then, give me the new section (*not* the entire document).  Where do I get the token? Maybe I should use a "JoinConfiguration" file, since I'm using Ansible?
