- name: Install packages neded to use the k8s apt repo
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Add the Kubernetes apt repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_release }}/deb/"
    suites: ["/"]
    signed_by: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_release }}/deb/Release.key"
    state: present

- name: Install k8s packages
  block:
    - name: Install kubelet, kubeadm, and kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - cri-tools
        state: present
        update_cache: true

    - name: Hold the Kubernetes packages
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubeadm
        - kubelet
        - kubectl
      register: __control_nodes_pkg_hold
      until: __control_nodes_pkg_hold is succeeded
      retries: 5
    delay: 12